// Generates src/assets/icons/*.svg from the re/read mark (reread-mark.svg in
// this directory, kept byte for byte as it left the design tool).
//
// The mark is drawn with one uniform line weight on an artboard the design
// tool trimmed to the drawing, so a single scale maps that artboard onto the
// full 16x16 Firefox toolbar grid. Full, not 15px like home.svg/reload.svg:
// the first cut sat 15px tall and read visibly shorter next to the avatar
// and puzzle buttons, which do run edge to edge (the avatar circle spans
// 0..16). The line weight lands at ~1.5px - the weight of the avatar
// button's ring, at the heavy end of the proton set (home/reload measure
// ~1.25px). Icon color tokens #5b5b66 (light theme) / #fbfbfe (dark theme)
// from tokens-shared.css.
//
// Three files, because three consumers: `icon.svg` follows the page's color
// scheme (default_icon, add-on manager), the fixed-color pair feeds
// action.theme_icons, where the active theme - not the OS scheme - decides.
//
// Usage: node tools/icon/make-icons.mjs

import { writeFile } from "node:fs/promises";

// The mark, in its own coordinates: a page outline and the letter r, on the
// artboard reread-mark.svg trims to the drawing.
const CANVAS = { w: 92.316, h: 101.265 };
const RECT = { x: 4.876, y: 4.925, w: 82.342, h: 91.262, rx: 14.764, stroke: 9.52 };
const GLYPH =
  "M31.858,57.057l-0.001,23.791l-10.515,-0l-0,-23.824l10.516,-0l0.001,-35.39l10.356,0.043" +
  "l0,5.393c0.291,-0.403 0.598,-0.792 0.921,-1.169c3.222,-3.758 7.863,-5.637 13.923,-5.637" +
  "c2.762,0 5.255,0.435 7.48,1.305c2.224,0.87 4.296,2.314 6.213,4.332l-6.789,6.367" +
  "c-1.15,-1.114 -2.416,-1.914 -3.797,-2.401c-1.381,-0.487 -2.992,-0.73 -4.833,-0.73" +
  "c-3.836,-0 -6.981,1.113 -9.436,3.34c-2.454,2.226 -3.682,5.601 -3.682,10.124l0,14.456l-10.357,-0Z";

// Outer bounds of the drawing, stroke included - reported so a resize of the
// artboard that clips the drawing would be visible in the output.
const outer = {
  x: RECT.x - RECT.stroke / 2,
  y: RECT.y - RECT.stroke / 2,
  w: RECT.w + RECT.stroke,
  h: RECT.h + RECT.stroke,
};

const S = 16 / CANVAS.h;
const DX = 8 - (CANVAS.w / 2) * S;
const DY = 8 - (CANVAS.h / 2) * S;

/** @param {number} n */
const round = (n) => {
  const r = Math.round(n * 1000) / 1000;
  return Object.is(r, -0) ? 0 : r;
};
/** @param {number} x */
const tx = (x) => round(x * S + DX);
/** @param {number} y */
const ty = (y) => round(y * S + DY);
/** @param {number} d */
const ts = (d) => round(d * S);

/**
 * Scale an SVG path of absolute M and relative l/c segments - all the mark
 * uses. Points move by the affine map, deltas only scale.
 *
 * @param {string} d
 */
function transformPath(d) {
  return d.replace(/([MlcZ])([^MlcZ]*)/g, (_, cmd, body) => {
    if (cmd === "Z") return "Z";
    const nums = String(body).match(/-?[\d.]+/g)?.map(Number) ?? [];
    /** @type {string[]} */
    const out = [];
    for (let i = 0; i + 1 < nums.length; i += 2) {
      const x = /** @type {number} */ (nums[i]);
      const y = /** @type {number} */ (nums[i + 1]);
      out.push(cmd === "M" ? `${tx(x)} ${ty(y)}` : `${ts(x)} ${ts(y)}`);
    }
    return cmd + out.join(" ");
  });
}

const rect =
  `x="${tx(RECT.x)}" y="${ty(RECT.y)}" width="${ts(RECT.w)}" height="${ts(RECT.h)}" ` +
  `rx="${ts(RECT.rx)}"`;
const strokeWidth = ts(RECT.stroke);
const glyph = transformPath(GLYPH);

/**
 * @param {string} paint - fill/stroke value ("currentColor" or a hex color)
 * @param {string} style - extra markup after the comment ("" for fixed colors)
 */
const svg = (paint, style) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <!-- The re/read mark: a page holding a single letter r. Drawn to match the
       Firefox toolbar set: ~1.5px lines, full-height on the 16px grid, the
       browser's icon color tokens #5b5b66 (light theme) / #fbfbfe (dark).
       Generated by tools/icon/make-icons.mjs - edit there, not here. -->
${style}  <rect ${rect} fill="none" stroke="${paint}" stroke-width="${strokeWidth}"/>
  <path d="${glyph}" fill="${paint}"/>
</svg>
`;

const adaptive = svg(
  "currentColor",
  `  <style>
    :root { color: #5b5b66; }
    @media (prefers-color-scheme: dark) { :root { color: #fbfbfe; } }
  </style>
`,
);

const OUT = new URL("../../src/assets/icons/", import.meta.url);
await writeFile(new URL("icon.svg", OUT), adaptive);
await writeFile(new URL("icon-dark.svg", OUT), svg("#5b5b66", ""));
await writeFile(new URL("icon-light.svg", OUT), svg("#fbfbfe", ""));
console.log("wrote icon.svg, icon-dark.svg, icon-light.svg");
console.log(`scale ${round(S)}, line ${strokeWidth}px, outer ${round(outer.w * S)}x${round(outer.h * S)}`);
