// Generates src/assets/icons/*.svg from the re/read mark (reread-mark.svg in
// this directory, kept byte for byte as it left the design tool).
//
// The mark is drawn on a 109x123 canvas with one uniform 8.33px line weight,
// so a single scale maps it onto the Firefox toolbar grid: 16x16, glyphs
// ~14-15px tall, ~1.25px lines (measured on home.svg and reload.svg of the
// proton set Firefox 153 ships by default), icon color tokens #5b5b66 (light
// theme) / #fbfbfe (dark theme) from tokens-shared.css. Scaling the drawing
// to 15px tall lands the line weight at 1.19px.
//
// Three files, because three consumers: `icon.svg` follows the page's color
// scheme (default_icon, add-on manager), the fixed-color pair feeds
// action.theme_icons, where the active theme - not the OS scheme - decides.
//
// Usage: node tools/icon/make-icons.mjs

import { writeFile } from "node:fs/promises";

// The mark, in its own coordinates: a page outline and the letter r.
const RECT = { x: 13.176, y: 13.176, w: 82.342, h: 96.404, rx: 7.915, stroke: 8.33 };
const GLYPH =
  "M42.962,67.235l-0.001,21.434l-8.438,0l0,-21.464l8.439,-0l0,-31.884l8.31,0.039l0,4.858" +
  "c0.234,-0.363 0.48,-0.714 0.739,-1.053c2.586,-3.385 6.31,-5.078 11.173,-5.078" +
  "c2.216,-0 4.216,0.392 6.001,1.175c1.785,0.784 3.447,2.085 4.986,3.903l-5.447,5.736" +
  "c-0.924,-1.003 -1.939,-1.724 -3.047,-2.163c-1.108,-0.438 -2.401,-0.658 -3.878,-0.658" +
  "c-3.078,0 -5.602,1.003 -7.572,3.009c-1.97,2.007 -2.955,5.047 -2.955,9.122l0,13.024l-8.31,-0Z";

// Outer bounds of the drawing, stroke included.
const outer = {
  x: RECT.x - RECT.stroke / 2,
  y: RECT.y - RECT.stroke / 2,
  w: RECT.w + RECT.stroke,
  h: RECT.h + RECT.stroke,
};

const S = 15 / outer.h;
const DX = 8 - (outer.x + outer.w / 2) * S;
const DY = 8 - (outer.y + outer.h / 2) * S;

/** @param {number} n */
const round = (n) => {
  const r = Math.round(n * 1000) / 1000;
  return Object.is(r, -0) ? 0 : r;
};
/** @param {number} x */
const tx = (x) => round(x * S + DX);
/** @param {number} y */
const ty = (y) => round(y * S + DY);
/** @param {number} d */
const ts = (d) => round(d * S);

/**
 * Scale an SVG path of absolute M and relative l/c segments - all the mark
 * uses. Points move by the affine map, deltas only scale.
 *
 * @param {string} d
 */
function transformPath(d) {
  return d.replace(/([MlcZ])([^MlcZ]*)/g, (_, cmd, body) => {
    if (cmd === "Z") return "Z";
    const nums = String(body).match(/-?[\d.]+/g)?.map(Number) ?? [];
    /** @type {string[]} */
    const out = [];
    for (let i = 0; i + 1 < nums.length; i += 2) {
      const x = /** @type {number} */ (nums[i]);
      const y = /** @type {number} */ (nums[i + 1]);
      out.push(cmd === "M" ? `${tx(x)} ${ty(y)}` : `${ts(x)} ${ts(y)}`);
    }
    return cmd + out.join(" ");
  });
}

const rect =
  `x="${tx(RECT.x)}" y="${ty(RECT.y)}" width="${ts(RECT.w)}" height="${ts(RECT.h)}" ` +
  `rx="${ts(RECT.rx)}"`;
const strokeWidth = ts(RECT.stroke);
const glyph = transformPath(GLYPH);

/**
 * @param {string} paint - fill/stroke value ("currentColor" or a hex color)
 * @param {string} style - extra markup after the comment ("" for fixed colors)
 */
const svg = (paint, style) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <!-- The re/read mark: a page holding a single letter r. Drawn to match the
       Firefox toolbar set: ~1.2px lines, 15px tall on the 16px grid, the
       browser's icon color tokens #5b5b66 (light theme) / #fbfbfe (dark).
       Generated by tools/icon/make-icons.mjs - edit there, not here. -->
${style}  <rect ${rect} fill="none" stroke="${paint}" stroke-width="${strokeWidth}"/>
  <path d="${glyph}" fill="${paint}"/>
</svg>
`;

const adaptive = svg(
  "currentColor",
  `  <style>
    :root { color: #5b5b66; }
    @media (prefers-color-scheme: dark) { :root { color: #fbfbfe; } }
  </style>
`,
);

const OUT = new URL("../../src/assets/icons/", import.meta.url);
await writeFile(new URL("icon.svg", OUT), adaptive);
await writeFile(new URL("icon-dark.svg", OUT), svg("#5b5b66", ""));
await writeFile(new URL("icon-light.svg", OUT), svg("#fbfbfe", ""));
console.log("wrote icon.svg, icon-dark.svg, icon-light.svg");
console.log(`scale ${round(S)}, line ${strokeWidth}px, outer ${round(outer.w * S)}x${round(outer.h * S)}`);
