// Generates src/assets/icons/*.svg from the re/read mark (reread-mark.svg in
// this directory, kept byte for byte as it left the design tool).
//
// The mark is drawn with one uniform line weight on an artboard the design
// tool trimmed to the drawing, so a single scale maps that artboard onto the
// full 16x16 Firefox toolbar grid. Full, not 15px like home.svg/reload.svg:
// the first cut sat 15px tall and read visibly shorter next to the avatar
// and puzzle buttons, which do run edge to edge (the avatar circle spans
// 0..16). The line weight lands at ~1.29px, within the proton set's ~1.25px
// (measured on home.svg and reload.svg of the set Firefox 153 ships by
// default). Icon color tokens #5b5b66 (light theme) / #fbfbfe (dark theme)
// from tokens-shared.css.
//
// Three files, because three consumers: `icon.svg` follows the page's color
// scheme (default_icon, add-on manager), the fixed-color pair feeds
// action.theme_icons, where the active theme - not the OS scheme - decides.
//
// Usage: node tools/icon/make-icons.mjs

import { writeFile } from "node:fs/promises";

// The mark, in its own coordinates: a page outline and the letter r, on the
// artboard reread-mark.svg trims to the drawing.
const CANVAS = { w: 90.722, h: 100.979 };
const RECT = { x: 4.231, y: 4.193, w: 82.342, h: 92.634, rx: 7.915, stroke: 8.17 };
const GLYPH =
  "M34.016,56.138l-0,20.596l-8.438,-0l0,-20.625l8.438,-0l0.001,-30.637l8.31,0.037l0,4.669" +
  "c0.234,-0.349 0.48,-0.686 0.739,-1.013c2.585,-3.253 6.309,-4.879 11.172,-4.879" +
  "c2.216,-0 4.217,0.376 6.002,1.129c1.785,0.753 3.447,2.003 4.986,3.75l-5.448,5.513" +
  "c-0.923,-0.964 -1.939,-1.657 -3.047,-2.079c-1.108,-0.421 -2.4,-0.632 -3.878,-0.632" +
  "c-3.077,-0 -5.601,0.964 -7.571,2.891c-1.97,1.928 -2.955,4.85 -2.955,8.765l0,12.515l-8.311,-0Z";

// Outer bounds of the drawing, stroke included - reported so a resize of the
// artboard that clips the drawing would be visible in the output.
const outer = {
  x: RECT.x - RECT.stroke / 2,
  y: RECT.y - RECT.stroke / 2,
  w: RECT.w + RECT.stroke,
  h: RECT.h + RECT.stroke,
};

const S = 16 / CANVAS.h;
const DX = 8 - (CANVAS.w / 2) * S;
const DY = 8 - (CANVAS.h / 2) * S;

/** @param {number} n */
const round = (n) => {
  const r = Math.round(n * 1000) / 1000;
  return Object.is(r, -0) ? 0 : r;
};
/** @param {number} x */
const tx = (x) => round(x * S + DX);
/** @param {number} y */
const ty = (y) => round(y * S + DY);
/** @param {number} d */
const ts = (d) => round(d * S);

/**
 * Scale an SVG path of absolute M and relative l/c segments - all the mark
 * uses. Points move by the affine map, deltas only scale.
 *
 * @param {string} d
 */
function transformPath(d) {
  return d.replace(/([MlcZ])([^MlcZ]*)/g, (_, cmd, body) => {
    if (cmd === "Z") return "Z";
    const nums = String(body).match(/-?[\d.]+/g)?.map(Number) ?? [];
    /** @type {string[]} */
    const out = [];
    for (let i = 0; i + 1 < nums.length; i += 2) {
      const x = /** @type {number} */ (nums[i]);
      const y = /** @type {number} */ (nums[i + 1]);
      out.push(cmd === "M" ? `${tx(x)} ${ty(y)}` : `${ts(x)} ${ts(y)}`);
    }
    return cmd + out.join(" ");
  });
}

const rect =
  `x="${tx(RECT.x)}" y="${ty(RECT.y)}" width="${ts(RECT.w)}" height="${ts(RECT.h)}" ` +
  `rx="${ts(RECT.rx)}"`;
const strokeWidth = ts(RECT.stroke);
const glyph = transformPath(GLYPH);

/**
 * @param {string} paint - fill/stroke value ("currentColor" or a hex color)
 * @param {string} style - extra markup after the comment ("" for fixed colors)
 */
const svg = (paint, style) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <!-- The re/read mark: a page holding a single letter r. Drawn to match the
       Firefox toolbar set: ~1.3px lines, full-height on the 16px grid, the
       browser's icon color tokens #5b5b66 (light theme) / #fbfbfe (dark).
       Generated by tools/icon/make-icons.mjs - edit there, not here. -->
${style}  <rect ${rect} fill="none" stroke="${paint}" stroke-width="${strokeWidth}"/>
  <path d="${glyph}" fill="${paint}"/>
</svg>
`;

const adaptive = svg(
  "currentColor",
  `  <style>
    :root { color: #5b5b66; }
    @media (prefers-color-scheme: dark) { :root { color: #fbfbfe; } }
  </style>
`,
);

const OUT = new URL("../../src/assets/icons/", import.meta.url);
await writeFile(new URL("icon.svg", OUT), adaptive);
await writeFile(new URL("icon-dark.svg", OUT), svg("#5b5b66", ""));
await writeFile(new URL("icon-light.svg", OUT), svg("#fbfbfe", ""));
console.log("wrote icon.svg, icon-dark.svg, icon-light.svg");
console.log(`scale ${round(S)}, line ${strokeWidth}px, outer ${round(outer.w * S)}x${round(outer.h * S)}`);
